### ISSUE TITLE
.dll or .cpp??

### ISSUE THREAD

**Issue by Ozzysyn** [rgcjonas/dd4seven#2]
I've been confused because in the README.md It says to find a dd4seven-api.dll and things of the sort.
But whenever I look up those I just get dd4seven-api.cpp, and the same thing happens with the other .dll files. I am confused whether to use these or not, and I am hesitant because this could harm my computer so I would like answers.

**Comment by rgcjonas** [comment]
The DLL files are not included, you need to compile them yourself from the .cpp source files. The `Makefile` should work for you (use a cross-compiler from linux, MSYS or cygwin are not supported).

Warning: This is not high-quality code. There is no guarantee that it works for you and it may very well cause undefined amounts of damage to your system. You should probably upgrade to Windows 8 or newer which contains the functionality natively. 

Feel free to reopen this issue if problems persist.
